# --- Cluster Secrets Generation ---

# 1. SSH Keypair for Inter-Node Communication
resource "tls_private_key" "cluster_ssh" {
  algorithm = "ED25519"
}


# Output public key for inspection (optional)
output "cluster_public_key" {
  value = tls_private_key.cluster_ssh.public_key_openssh
}

# --- Admin Access Key (Generated by Terraform) ---

resource "tls_private_key" "admin_ssh" {
  algorithm = "ED25519"
}

resource "aws_key_pair" "admin_key" {
  key_name   = var.ssh_key_name
  public_key = tls_private_key.admin_ssh.public_key_openssh
}

resource "local_file" "admin_private_key" {
  content         = tls_private_key.admin_ssh.private_key_openssh
  filename        = "${path.module}/${var.ssh_key_name}.pem"
  file_permission = "0600"
}
